import { db, pool, schemesTable, type InsertScheme } from "./index";

const allIndia = ["All India"];
const seeds: InsertScheme[] = [
  {
    name: "PM-KISAN Samman Nidhi",
    category: "Agriculture",
    description: "Income support for eligible landholding farmer families, subject to the scheme's exclusions and land-record verification.",
    benefits: "Direct income support of ₹6,000 per year, paid in three installments to eligible farmer families.",
    minAge: null,
    maxAge: null,
    maxIncome: null,
    gender: null,
    states: allIndia,
    categoriesAllowed: [],
    occupations: ["Farmer"],
    isStudent: null,
    isFarmer: true,
    hasDisability: null,
    documentsRequired: ["Aadhaar", "Bank account details", "Land records"],
    applyUrl: "https://pmkisan.gov.in/",
  },
  {
    name: "Ayushman Bharat PM-JAY",
    category: "Healthcare",
    description: "Hospitalization cover for eligible low-income and vulnerable households identified through notified criteria and state extensions.",
    benefits: "Cashless secondary and tertiary hospitalization cover up to ₹5 lakh per eligible family per year.",
    minAge: null,
    maxAge: null,
    maxIncome: null,
    gender: null,
    states: allIndia,
    categoriesAllowed: [],
    occupations: [],
    isStudent: null,
    isFarmer: null,
    hasDisability: null,
    documentsRequired: ["Aadhaar or other accepted identity proof", "Ration card or family identification details"],
    applyUrl: "https://beneficiary.nha.gov.in/",
  },
  {
    name: "Pradhan Mantri Awas Yojana - Urban 2.0",
    category: "Housing",
    description: "Housing support for eligible urban families who do not own a pucca house anywhere in India; component rules and household income bands apply.",
    benefits: "Assistance through eligible PMAY-U 2.0 components, including interest subsidy or support for house construction, subject to current guidelines.",
    minAge: 18,
    maxAge: null,
    maxIncome: 900000,
    gender: null,
    states: allIndia,
    categoriesAllowed: [],
    occupations: [],
    isStudent: null,
    isFarmer: null,
    hasDisability: null,
    documentsRequired: ["Aadhaar", "Income proof", "Bank account details", "Proof of residence", "Household and property details"],
    applyUrl: "https://pmay-urban.gov.in/",
  },
  {
    name: "Pradhan Mantri Awaas Yojana - Gramin",
    category: "Housing",
    description: "Rural housing assistance for eligible households identified through official deprivation and beneficiary-list criteria.",
    benefits: "Financial assistance for construction of a pucca house, with amounts and additional support determined by location and current guidelines.",
    minAge: 18,
    maxAge: null,
    maxIncome: null,
    gender: null,
    states: allIndia,
    categoriesAllowed: [],
    occupations: [],
    isStudent: null,
    isFarmer: null,
    hasDisability: null,
    documentsRequired: ["Aadhaar", "Rural household details", "Bank account details", "Beneficiary-list verification"],
    applyUrl: "https://pmayg.nic.in/",
  },
  {
    name: "Pradhan Mantri MUDRA Yojana",
    category: "Business",
    description: "Credit support for eligible non-corporate, non-farm micro and small business activities through participating lenders.",
    benefits: "Business loans through Shishu, Kishor, Tarun and Tarun Plus categories; loan size and approval depend on the lender and eligibility.",
    minAge: 18,
    maxAge: null,
    maxIncome: null,
    gender: null,
    states: allIndia,
    categoriesAllowed: [],
    occupations: [],
    isStudent: null,
    isFarmer: null,
    hasDisability: null,
    documentsRequired: ["Identity proof", "Address proof", "Business plan or activity details", "Bank statements", "Lender application forms"],
    applyUrl: "https://www.mudra.org.in/",
  },
  {
    name: "Sukanya Samriddhi Account",
    category: "Savings",
    description: "Small-savings account opened by a parent or guardian for a girl child who is below 10 years old at account opening.",
    benefits: "Long-term, government-backed savings account with interest notified periodically; tax treatment and withdrawal rules are set by current rules.",
    minAge: 0,
    maxAge: 9,
    maxIncome: null,
    gender: "Female",
    states: allIndia,
    categoriesAllowed: [],
    occupations: [],
    isStudent: null,
    isFarmer: null,
    hasDisability: null,
    documentsRequired: ["Girl child's birth certificate", "Parent or guardian identity proof", "Address proof", "Initial deposit"],
    applyUrl: "https://www.nsiindia.gov.in/",
  },
  {
    name: "Atal Pension Yojana",
    category: "Pension",
    description: "Voluntary pension scheme for eligible Indian citizens aged 18 to 40 with a savings bank or post-office account; tax-payer restrictions apply to new enrollments.",
    benefits: "A guaranteed minimum monthly pension option from age 60, based on the selected contribution slab and scheme rules.",
    minAge: 18,
    maxAge: 40,
    maxIncome: null,
    gender: null,
    states: allIndia,
    categoriesAllowed: [],
    occupations: [],
    isStudent: null,
    isFarmer: null,
    hasDisability: null,
    documentsRequired: ["Savings bank or post-office account", "Aadhaar", "Mobile number", "Nominee details"],
    applyUrl: "https://npscra.nsdl.co.in/scheme-details.php",
  },
  {
    name: "Pradhan Mantri Ujjwala Yojana",
    category: "Energy",
    description: "LPG connection support for adult women in eligible low-income households that do not already have an LPG connection, subject to current criteria.",
    benefits: "Deposit-free LPG connection support and applicable initial refill or stove assistance as notified by the scheme.",
    minAge: 18,
    maxAge: null,
    maxIncome: null,
    gender: "Female",
    states: allIndia,
    categoriesAllowed: [],
    occupations: [],
    isStudent: null,
    isFarmer: null,
    hasDisability: null,
    documentsRequired: ["Aadhaar", "Ration card or family composition proof", "Bank account details", "Address proof"],
    applyUrl: "https://www.pmuy.gov.in/",
  },
  {
    name: "Stand-Up India",
    category: "Business",
    description: "Bank credit for greenfield enterprises promoted by women entrepreneurs or entrepreneurs from Scheduled Caste or Scheduled Tribe communities.",
    benefits: "Composite bank loans for eligible greenfield projects; loan amount, margin and sanction are decided under current guidelines and lender appraisal.",
    minAge: 18,
    maxAge: null,
    maxIncome: null,
    gender: null,
    states: allIndia,
    categoriesAllowed: [],
    occupations: [],
    isStudent: null,
    isFarmer: null,
    hasDisability: null,
    documentsRequired: ["Identity and address proof", "Business plan", "Project cost details", "Category or ownership proof where applicable"],
    applyUrl: "https://www.standupmitra.in/",
  },
  {
    name: "Post-Matric Scholarship for SC Students",
    category: "Education",
    description: "Scholarship support for eligible Scheduled Caste students studying in post-matriculation or post-secondary courses, subject to state and course rules.",
    benefits: "Eligible tuition and maintenance support according to course group, institution and current scholarship guidelines.",
    minAge: null,
    maxAge: null,
    maxIncome: 250000,
    gender: null,
    states: allIndia,
    categoriesAllowed: ["SC"],
    occupations: [],
    isStudent: true,
    isFarmer: null,
    hasDisability: null,
    documentsRequired: ["Caste certificate", "Income certificate", "Previous examination marksheet", "Admission proof", "Bank account details"],
    applyUrl: "https://scholarships.gov.in/",
  },
  {
    name: "National Means-cum-Merit Scholarship Scheme",
    category: "Education",
    description: "Merit-based scholarship for selected students from economically weaker sections continuing from Class IX to Class XII in eligible schools.",
    benefits: "Scholarship assistance for selected students, subject to qualifying examination, school, attendance and renewal conditions.",
    minAge: null,
    maxAge: null,
    maxIncome: 350000,
    gender: null,
    states: allIndia,
    categoriesAllowed: [],
    occupations: [],
    isStudent: true,
    isFarmer: null,
    hasDisability: null,
    documentsRequired: ["Class VII/VIII marksheets", "Income certificate", "School enrollment proof", "Bank account details"],
    applyUrl: "https://scholarships.gov.in/",
  },
  {
    name: "Central Sector Scheme of Scholarship for College and University Students",
    category: "Education",
    description: "Scholarship for eligible meritorious students from low-income families pursuing regular undergraduate or postgraduate studies.",
    benefits: "Annual scholarship assistance at rates set for the course level and current scheme guidelines.",
    minAge: null,
    maxAge: null,
    maxIncome: 450000,
    gender: null,
    states: allIndia,
    categoriesAllowed: [],
    occupations: [],
    isStudent: true,
    isFarmer: null,
    hasDisability: null,
    documentsRequired: ["Class XII marksheet", "Income certificate", "College admission proof", "Bank account details"],
    applyUrl: "https://scholarships.gov.in/",
  },
  {
    name: "PM Vishwakarma",
    category: "Skills",
    description: "Support for traditional artisans and craftspeople working with their hands and tools in one of the scheme's notified trades.",
    benefits: "Recognition, skill training, toolkit incentive, concessional credit and other support subject to verification and scheme rules.",
    minAge: 18,
    maxAge: null,
    maxIncome: null,
    gender: null,
    states: allIndia,
    categoriesAllowed: [],
    occupations: ["Carpenter", "Boat Maker", "Blacksmith", "Locksmith", "Goldsmith", "Potter", "Sculptor", "Stone Mason", "Cobbler", "Mason", "Basket Weaver", "Doll Maker", "Barber", "Garland Maker", "Washerman", "Tailor", "Fishing Net Maker"],
    isStudent: null,
    isFarmer: null,
    hasDisability: null,
    documentsRequired: ["Aadhaar", "Mobile number", "Bank account details", "Trade and family details"],
    applyUrl: "https://pmvishwakarma.gov.in/",
  },
  {
    name: "PM Street Vendor's AtmaNirbhar Nidhi (PM SVANidhi)",
    category: "Business",
    description: "Working-capital support for street vendors who meet the urban local body and scheme identification requirements.",
    benefits: "Collateral-free working-capital loan tranches with interest subsidy and digital-transaction incentives as permitted by current rules.",
    minAge: 18,
    maxAge: null,
    maxIncome: null,
    gender: null,
    states: allIndia,
    categoriesAllowed: [],
    occupations: ["Street Vendor"],
    isStudent: null,
    isFarmer: null,
    hasDisability: null,
    documentsRequired: ["Certificate of vending or letter of recommendation", "Aadhaar", "Bank account details", "Mobile number"],
    applyUrl: "https://pmsvanidhi.mohua.gov.in/",
  },
  {
    name: "Pradhan Mantri Jeevan Jyoti Bima Yojana",
    category: "Insurance",
    description: "Renewable one-year life insurance cover available through participating banks and post offices to eligible account holders.",
    benefits: "Life cover of ₹2 lakh for death due to any cause during the period of cover, subject to policy terms.",
    minAge: 18,
    maxAge: 50,
    maxIncome: null,
    gender: null,
    states: allIndia,
    categoriesAllowed: [],
    occupations: [],
    isStudent: null,
    isFarmer: null,
    hasDisability: null,
    documentsRequired: ["Savings bank or post-office account", "Consent for premium auto-debit", "Identity proof"],
    applyUrl: "https://jansuraksha.gov.in/",
  },
  {
    name: "Pradhan Mantri Suraksha Bima Yojana",
    category: "Insurance",
    description: "Renewable personal accident insurance cover for eligible bank or post-office account holders aged 18 to 70.",
    benefits: "Accidental death and disability cover according to the policy schedule and current terms.",
    minAge: 18,
    maxAge: 70,
    maxIncome: null,
    gender: null,
    states: allIndia,
    categoriesAllowed: [],
    occupations: [],
    isStudent: null,
    isFarmer: null,
    hasDisability: null,
    documentsRequired: ["Savings bank or post-office account", "Consent for premium auto-debit", "Identity proof"],
    applyUrl: "https://jansuraksha.gov.in/",
  },
  {
    name: "Pradhan Mantri Shram Yogi Maandhan",
    category: "Pension",
    description: "Contributory pension scheme for eligible unorganised workers aged 18 to 40 with monthly income up to ₹15,000, subject to exclusions.",
    benefits: "Assured monthly pension from age 60 under the contribution and government co-contribution rules.",
    minAge: 18,
    maxAge: 40,
    maxIncome: 180000,
    gender: null,
    states: allIndia,
    categoriesAllowed: [],
    occupations: ["Unorganised Worker"],
    isStudent: null,
    isFarmer: null,
    hasDisability: null,
    documentsRequired: ["Aadhaar", "Savings bank or Jan-Dhan account", "Mobile number", "Occupation details"],
    applyUrl: "https://maandhan.in/",
  },
  {
    name: "Pradhan Mantri Fasal Bima Yojana",
    category: "Agriculture",
    description: "Crop insurance for farmers growing notified crops in notified areas, subject to season enrollment and state notifications.",
    benefits: "Insurance protection against specified crop losses under the notified season's terms and premium rules.",
    minAge: null,
    maxAge: null,
    maxIncome: null,
    gender: null,
    states: allIndia,
    categoriesAllowed: [],
    occupations: ["Farmer"],
    isStudent: null,
    isFarmer: true,
    hasDisability: null,
    documentsRequired: ["Aadhaar", "Land or tenancy records", "Sowing details", "Bank account details"],
    applyUrl: "https://pmfby.gov.in/",
  },
  {
    name: "National Overseas Scholarship",
    category: "Education",
    description: "Scholarship support for eligible students from specified disadvantaged communities pursuing approved postgraduate or doctoral studies abroad.",
    benefits: "Tuition, maintenance and other assistance as prescribed by the current guidelines and approved award.",
    minAge: null,
    maxAge: 35,
    maxIncome: 800000,
    gender: null,
    states: allIndia,
    categoriesAllowed: ["SC", "DNT", "Landless Agricultural Labourer", "Traditional Artisan"],
    occupations: [],
    isStudent: true,
    isFarmer: null,
    hasDisability: null,
    documentsRequired: ["Community certificate", "Income certificate", "Admission offer", "Academic records", "Passport"],
    applyUrl: "https://nosmsje.gov.in/",
  },
  {
    name: "Indira Gandhi National Old Age Pension Scheme",
    category: "Pension",
    description: "Social assistance pension for eligible older people from below-poverty-line households; state top-ups and enrollment rules vary.",
    benefits: "Monthly pension assistance, with central and state amounts determined by age, state and current rules.",
    minAge: 60,
    maxAge: null,
    maxIncome: null,
    gender: null,
    states: allIndia,
    categoriesAllowed: [],
    occupations: [],
    isStudent: null,
    isFarmer: null,
    hasDisability: null,
    documentsRequired: ["Age proof", "Residence proof", "BPL or eligibility-list verification", "Bank account details"],
    applyUrl: "https://nsap.nic.in/",
  },
  {
    name: "Indira Gandhi National Widow Pension Scheme",
    category: "Pension",
    description: "Social assistance pension for eligible widows in the notified age band from below-poverty-line households, with state rules and top-ups.",
    benefits: "Monthly pension assistance according to age, state and current scheme rules.",
    minAge: 40,
    maxAge: 79,
    maxIncome: null,
    gender: "Female",
    states: allIndia,
    categoriesAllowed: [],
    occupations: [],
    isStudent: null,
    isFarmer: null,
    hasDisability: null,
    documentsRequired: ["Age proof", "Residence proof", "Widow certificate", "BPL or eligibility-list verification", "Bank account details"],
    applyUrl: "https://nsap.nic.in/",
  },
  {
    name: "Indira Gandhi National Disability Pension Scheme",
    category: "Pension",
    description: "Social assistance pension for eligible people with severe or multiple disabilities in the notified age band and below-poverty-line households.",
    benefits: "Monthly pension assistance, with state additions and enrollment terms varying by location.",
    minAge: 18,
    maxAge: 79,
    maxIncome: null,
    gender: null,
    states: allIndia,
    categoriesAllowed: [],
    occupations: [],
    isStudent: null,
    isFarmer: null,
    hasDisability: true,
    documentsRequired: ["Disability certificate", "Age proof", "Residence proof", "BPL or eligibility-list verification", "Bank account details"],
    applyUrl: "https://nsap.nic.in/",
  },
  {
    name: "PM Surya Ghar: Muft Bijli Yojana",
    category: "Energy",
    description: "Rooftop solar support for eligible residential electricity consumers, with subsidy and installation rules set by current guidelines.",
    benefits: "Central financial assistance for eligible rooftop solar installations; capacity, vendor and disbursement conditions apply.",
    minAge: 18,
    maxAge: null,
    maxIncome: null,
    gender: null,
    states: allIndia,
    categoriesAllowed: [],
    occupations: [],
    isStudent: null,
    isFarmer: null,
    hasDisability: null,
    documentsRequired: ["Electricity consumer account details", "Aadhaar or accepted identity proof", "Bank account details"],
    applyUrl: "https://pmsuryaghar.gov.in/",
  },
  {
    name: "Pradhan Mantri Jan-Dhan Yojana",
    category: "Financial Inclusion",
    description: "Financial inclusion program providing access to a basic bank account and eligible linked services.",
    benefits: "Basic savings account access and eligibility for linked services such as RuPay card and insurance, subject to current terms.",
    minAge: 10,
    maxAge: null,
    maxIncome: null,
    gender: null,
    states: allIndia,
    categoriesAllowed: [],
    occupations: [],
    isStudent: null,
    isFarmer: null,
    hasDisability: null,
    documentsRequired: ["Aadhaar or accepted identity proof", "Address proof"],
    applyUrl: "https://pmjdy.gov.in/",
  },
  {
    name: "Kisan Credit Card",
    category: "Agriculture",
    description: "Credit facility for eligible farmers and certain animal-husbandry or fisheries activities through participating banks.",
    benefits: "Flexible agricultural credit for eligible production and related expenses; limit, interest benefit and approval are determined by the lender and rules.",
    minAge: 18,
    maxAge: null,
    maxIncome: null,
    gender: null,
    states: allIndia,
    categoriesAllowed: [],
    occupations: ["Farmer"],
    isStudent: null,
    isFarmer: true,
    hasDisability: null,
    documentsRequired: ["Identity proof", "Address proof", "Land or activity records", "Bank application documents"],
    applyUrl: "https://www.myscheme.gov.in/schemes/kcc",
  },
];

async function seed(): Promise<void> {
  await db.insert(schemesTable).values(seeds).onConflictDoNothing({
    target: schemesTable.name,
  });
  const rows = await db.select({ id: schemesTable.id }).from(schemesTable);
  console.info(`Scheme catalog ready (${rows.length} rows; ${seeds.length} supplied).`);
}

try {
  await seed();
} finally {
  await pool.end();
}
